# Generated by Django 4.2.3 on 2023-10-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_feedbacks_user_feedbacks_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='message_group',
            field=models.IntegerField(null=True),
        ),
    ]
