# Generated by Django 4.2.3 on 2023-10-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_feedbacks_message_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='approved',
            field=models.IntegerField(null=True),
        ),
    ]
