# Generated by Django 4.2.3 on 2023-10-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_feedbacks_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_KEY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField()),
            ],
        ),
    ]
